### ISSUE TITLE
Gutter width seems to always be 30px

### ISSUE THREAD

**Issue by GRardB** [ChilliCream/react-rasta#38]
Hey,

I've been checking out this library for a new project I'm working on. I've got the following:

```
// other imports
import { Theme, ThemeProvider } from 'react-rasta';

const theme: Theme = {
  gutterWidth: 20,
}

export const App = () => (
  <Provider>
    <ThemeProvider theme={theme}>
      <Router>
        <Routes />
      </Router>
    </ThemeProvider>
  </Provider>
)
```

However, the gutter width seems to stay 30px in my app:

![image](https://user-images.githubusercontent.com/748180/41195153-418cc868-6bdd-11e8-9483-77e70291149f.png)

Am I doing something wrong?

**Comment by rstaib** [comment]
Thank you for reporting. Fixed in version 1.0.2.
